import { AlbumRow } from '../types'

interface ExportData {
  albums: AlbumRow[]
  timeWindow: string
  exportDate: string
  totalPlays: number
  totalMinutes: number
  totalAlbums: number
}

export function exportToJSON(data: ExportData): void {
  const jsonData = JSON.stringify(data, null, 2)
  const blob = new Blob([jsonData], { type: 'application/json' })
  downloadFile(blob, `spotify-data-${data.timeWindow}-${Date.now()}.json`)
}

export function exportToCSV(albums: AlbumRow[], timeWindow: string): void {
  // CSV header
  let csv = 'Album ID,Album Name,Play Count,Minutes Listened,Last Played Date\n'
  
  // CSV rows
  albums.forEach(album => {
    const lastPlayedDate = album.last_played 
      ? new Date(album.last_played).toISOString().split('T')[0] 
      : 'N/A'
    
    const albumName = `"${album.album_name.replace(/"/g, '""')}"` // Escape quotes
    
    csv += `${album.album_id},${albumName},${album.plays},${album.minutes || 0},${lastPlayedDate}\n`
  })
  
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  downloadFile(blob, `spotify-albums-${timeWindow}-${Date.now()}.csv`)
}

export function generateMarkdownReport(data: ExportData): void {
  const { albums, timeWindow, totalPlays, totalMinutes, totalAlbums } = data
  const date = new Date().toLocaleDateString('zh-TW')
  
  let markdown = `# Spotify 聆聽分析報告

**生成日期**: ${date}  
**分析週期**: ${getTimeWindowLabel(timeWindow)}  
**總專輯數**: ${totalAlbums}  
**總播放次數**: ${totalPlays.toLocaleString()}  
**總聆聽時長**: ${formatMinutes(totalMinutes)}  

## Top 20 專輯排行榜

| 排名 | 專輯名稱 | 播放次數 | 聆聽時長 | 最後播放 |
|------|----------|----------|----------|----------|
`
  
  albums.slice(0, 20).forEach((album, index) => {
    const lastPlayed = album.last_played 
      ? new Date(album.last_played).toLocaleDateString('zh-TW') 
      : 'N/A'
    
    markdown += `| ${index + 1} | ${album.album_name} | ${album.plays} | ${formatMinutes(album.minutes || 0)} | ${lastPlayed} |\n`
  })
  
  markdown += `\n---\n*Generated by Spotify Crate*`
  
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8;' })
  downloadFile(blob, `spotify-report-${timeWindow}-${Date.now()}.md`)
}

function downloadFile(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function getTimeWindowLabel(window: string): string {
  const labels: Record<string, string> = {
    '7d': '過去 7 天',
    '30d': '過去 30 天',
    '180d': '過去半年',
    '365d': '過去一年'
  }
  return labels[window] || window
}

function formatMinutes(minutes: number): string {
  const hours = Math.floor(minutes / 60)
  const mins = Math.round(minutes % 60)
  return hours > 0 ? `${hours} 小時 ${mins} 分鐘` : `${mins} 分鐘`
}